---

- name: Converge for host-server
  hosts: lamp-servers


  roles:
    - role: shareable-ansible-toolkit/nginx-lxd-forward-proxy
      forward_domains: "french.kwiziq.vubuntu.spottmedia.co.uk spanish.kwiziq.vubuntu.spottmedia.co.uk kwiziq.vubuntu.spottmedia.co.uk api.kwiziq.vubuntu.spottmedia.co.uk"   # space separated list of domains (NGINX format)

  tags:
    - host-server
    - never

- name: Converge for all
  hosts: all

  roles:
    - shareable-ansible-toolkit/common-dev

  tags:
    - all-servers


- name: Converge for lamp
  hosts: lamp-servers

  roles:
    - shareable-ansible-toolkit/apache_base
    - shareable-ansible-toolkit/apachewebtier
    - shareable-ansible-toolkit/apache-vhosts-role
    - shareable-ansible-toolkit/dev-mysql

  tags:
    - lamp-servers